apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:YT45l4v1HT0RMrU6XnajYJs7qyEypTBiUe3wxkU1SorIC7HB,iv:DKxHy9oyrI5kh7cQf+VNA5R5BnX3EwtKNEy4xptu+6w=,tag:XWA6vV8BTIZEchyScjRHtw==,type:str]
    credentials.json: ENC[AES256_GCM,data:whPpzEU+T0a2cJ2rlRQxx7cJw4vkR+PZegdIXi2ERhs+fkfchR3VFnv/1Ltpun7h+m/LIYA3lpMMxmGQ3qRCz44NePDnTRQMkjcaulZHat8UpLvTaLGcA3lmycioTJTJEtXmAMWOWl6C/cbS6AlbOBEKTgpaeTOswimPSEK/cz9g5GTy+3QzV3uyDC/am3iT67QvpLBqrBYv7R6rRyNdt8asrb9Tn+ZBUXzYkSMprA==,iv:xtHdDsp1SbNeI1NY8gOnJYCzIRsEh6N0UszEEfAg8EQ=,tag:PDo+DmBA6+OzOeIat7cqmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QkZHc3R4U1Mwb0V0dElQ
            R1hIQmUvaTQ1VHRoSnJVbnhPc00zb3d3TWlvCi95Q25jcjBxU3ZhcXdIUE52aXZC
            bTdvcDB0dENEYUVuTW1YcXY3aEZRQmMKLS0tIHBnNStCUUx6Z2FvR2ppZERGc1dp
            cHA5b2VnSHJFY2t6Y1RKR3d6L1ZyS1EKSUFfe0kTR9hOfwLP9auxf0JccZFda4gl
            PzNCuAUjrcIEtgffpXDD2SwB+d6jR7UhqEkL5vtbuBVycMZ75kR9lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T07:48:37Z"
    mac: ENC[AES256_GCM,data:+y/HV6mj0/oDaKRM3AsZdVseX7fsm7g/uSI6f+D4F+sLbbxv5VsdOuzlBgKHUEDGz5nBbbpYz8d8jQ6PzcDs4BGSGjSHVmMpT19vKSLOKuU7tvgj4HnlvF8BmWHVXesnxhq3FWisLgOaoeai0JP4429pUSFVNzqK08EcXbVIJXM=,iv:TaU6uIyGhLy2yuUOFo0CATQnkjDBAgzvNJsCQQO0Nlc=,tag:Kj3XQuNesYOnyyh6f41l3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
