apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:uRtUWqhAOq//VJPREtkeANSHytgv5kutZvZprV44EaLK+9Mt,iv:yb26f+874IGDRp5QR8e/Yid+8LmBR6JMjry+2uRFArU=,tag:wCWg++t/pKCZfBh8zsWxEA==,type:str]
    credentials.json: ENC[AES256_GCM,data:DT84qWJUunQrq5/T1nzQUXDYsBBQf2U8bv8AbmPMUgkWzZSrIGHsuwOzrIYiwIFScn5p5ENo6+mC5eARGZr2XBHSxUuG2Nvg94k5dD0oqftw1dYJfsxi0d/qpHQCo25Js+BDSSDpUuO/QQXvX00TJ95IXTrblgjNYGYgMTY0pUJElD43O9lE5Yd4QPL6uI7Z1+7zlmYVYrh8bSfqFu1FCQMJpWCuhPm4ia0Jurt97w==,iv:23xQz+etDgeMiKPjQQvbxpgRuwxXLZYVgTcBWYSRyJk=,tag:QiwrEjvHclQfWUN37iJvPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZVo4Z3ZManEvQmIvNXlP
            L0pVRHRQOWlOd240cm9PejdDdDR5MTM2T3pFCjBoNlZtR0p5KytLM21VaFVNT1Ri
            eG0ramplUVFPOW9HMWhRcVErMXZrMGsKLS0tIDVRUHZaQitlbUhMdTFFRkgvMUpz
            cVlIcEcxZVNUc2tFMUpJMHFPS0dMRGMK1655MGoeEAQj1LLWQ+4HwuIch6J/E9CO
            Fnj5rQIzxBU9iW27aYB3R19FCRs+Oq9z2uAZdEJIca+ar+wmL4kuCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:59:31Z"
    mac: ENC[AES256_GCM,data:RU9yFDJXppqrFN7/R34pL//crvhOElEGA2+Upes8NQ7QDor+ClJATVz5erCU/DS/Beyll2Tlct+p0lvqIBKaJQdYrWTuC6IFTsvYMcXA1on8WpkpcvgG0ENvrsDJzRuGBuMnBqTXQUB5LA6H3cZbDs5HOnlGfb9FWgTJsSY8BCM=,iv:rGH/QpBAN5sXPhGhFt8fElcLAjQX97YqJv2UZ0iLjuo=,tag:FlR/1euOljCOmjZMCYeUfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
