apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:clMmMKzG1VVU5SiloSkeT+IuHC0Nukshmn4Cg6zB0L8oa3WGVSd3xA==,iv:KTQTFR2xeaJXqhkmcnw0sTFIj2pT1AcGpJRAPIpp/s0=,tag:tT+5Akv91hD7aPfzRWgaCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTemZrRkgvVmVCZWdHNE81
            S01YQUpsWkwwN0tmVE9ZZ20wRnViWVdjSFJ3CjdUZ3gzdW1TeWJ3RkdrZlQwcUs2
            NE0yZi9EZmdXckNINEo0MysyL2tta3cKLS0tIGkzNVFYVmVzb3RtRGZtbzRxdjhq
            UlpkdTh5RWU1cUVrdS94YTQ2cTJScm8KSf1GsIIqMzAQnmmxQZxhP9WQY6mmTc1F
            ydblycMYhk47ykEImKClv1kUtpOWVWVAyfrABRd4Hlu8xM5ZddMG7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:59:31Z"
    mac: ENC[AES256_GCM,data:/jo3r8Z+QiJr2uW5/04Nblxl/X/npeZ2XV2gotjqWXYNZpWGEIOzYu4NnlrYgoQQoxrcKLLXWBggY91eNT/MpJ3Z+uub0MlM0CbVlNs52g4wg1MJ+iTW45yxEQ6E6s/N4Kq7AKFCeSicKTAZkDf0XwSEB7hgAmCIIETUw8xIStg=,iv:G11HhUKlAlNv3Ik0mDg3yE3lSqEUCI9K2Tl6oEJ3eSE=,tag:713AcHFHUjucvff42IvZIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
