apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:btSZOJI9Knz6bh1m60DE6WocgAsmDpiGIJ/o4QBxY0qoDMOUgVGsFg==,iv:sBewzF5CkIi487WsQ/0rfLsI+d0yx8eeu1TFZMcoLkM=,tag:ssMdPqVlBrTe1SWcxxPqEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcENyQXdsSDhocTZreWNt
            ODBYdDlsVm9mOUVJbDAwWW00bGt5SUt6eno0CjF3U0hoNEM2Z09ubTBNcStqT25v
            aXFWR2o4L1YwSksxWm93cjY4SGNGaVkKLS0tIFpUSkFQWHNCWnBrRWJ2dm9qdDQz
            cDQ1VWJOSmo0QlZCQXpsV1BuUDVvWUUKkyTIKCakvltt1lOGFYfV5Lx1nmCOqHDp
            INY93YiiVo7IXVmamtNEeF2Lb6lz2tzr1vqF8RoB8zNReb5Kd0mXyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T07:48:37Z"
    mac: ENC[AES256_GCM,data:ITG0OqvrdvebB7d3bhYQ3EhXa+hhFzcu/5OilK84Ozs3lFZ3dfEiWpqTKuDlZ0ascSvjqCQGRgGQVHWCA9RDhYwTNtdSAuwMIzenzd3DEk9CLF1O/pWKyklT/eU1DMjGFU1Xc7Wk3DPn9igKxIQopNyjAnZdfIOcgcJdlG2EiW4=,iv:SWZ4zEK8I3oi2UDTuQOjn6CO4GHf24VlVVedNvDhCow=,tag:BEhkGWcGSwITEZJOKt1YHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
