apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5+V5IyM=,iv:ICBS2XVis1cL7oDyp7FCqtib+6BOMLJFItE1u88hXhg=,tag:LnyAEuOJTQqULm2Kbl23Gw==,type:str]
    password: ENC[AES256_GCM,data:TPL+cP/19m5+q9XKE9YD99lJeXlWZbXOCD7hQKfhiPQEcVeR+omImYPj5gNxJ1FZDybypPBPPqLyxnWZ,iv:zqxI1Gwrg1K1ExTTavHuk4fct1+kXswFBkJEhPadMn4=,tag:eAVysOSA3GfByG39pQQkKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ0hmaW1kZWNOK0lIdXBn
            SHdyMUtVVyt0c1RzOWNLUm1wNnVLdmxla1RrClVKWHRmejVNQ3gyMk1hQVFLOTVF
            NVhTMmZ3cnZzUmRsckM0N0N4Y3NjU0EKLS0tIG9ST3ZCUHppa2RrR09MUnI1WnRP
            eTZDOEFjWlREZ1lneUFHM1VudlBxV2sKPSS/+/xdYmhAL/bSH6huECekhDoXUh4m
            MiGJHd6zDtQWXO72X62HOcZI8ETGGOg5/8OrUD01rIvlz7MdZfrAEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T07:48:37Z"
    mac: ENC[AES256_GCM,data:z3PPhHmcG6Va+VwzWfjEX1Jip+b9DnhOEkOggV+YC9JUy8TYgxLb7/qCGe3MAZDymGkh7tuJI2zhOtk46gH6qcE3vrLLRd8idYr04zWE2HC3ayOiFOBSGVXLaWqfkdrjfmK+sYdA7E6bcjdTXaqvebwjf4NeWdu+8cFudp/3030=,iv:pVmiseDFQylINMjFg+dvfJ/Z8Yp5BWcESSSY6+o1w/w=,tag:9TB+TVOQ07/Em3+ol2y/KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
