apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:gGrfK7E=,iv:vjoJTBPrn4LFPkwZW6mX/6TrfCNi18ui/lma7tnToWw=,tag:RUifbooPVzgzNsp56cQ7Lg==,type:str]
    password: ENC[AES256_GCM,data:Sa2YvR87ODke6YrIOghoYFNU98OFowLWT551rjuyUZkaNv0ll2HKg8v/jAd4Zk2m0s32vNuLZeZrosQX,iv:DUROxGWBOx2nYMB3I/7avhCiSSECr6nahCv0sB24cIE=,tag:i7MJ/EkyQCFGrcUAmKdnEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUmpqNUVMREtic3FFWnFn
            cVk4eWpuRDJCeVRPWWhUZCtrWmNkUkJxa25FCmF5WWl5NFhZRVRIbGU1UHF3T0lQ
            Mm1kUmdkQ2YvcU9PN0RZenh0YXVtRTAKLS0tIHc2QzFNMXJCcXdHem5TVFIyd29j
            NjFRRXh3bklka0Q5ODNDaW1vOWUyNzQKmX3xLV6EQ2eS1YE/4W6eUUKLVt1doBa1
            aUNZze69lAil752pPCEpf2bKnHa9HmLKW5AF6021st1aFhwlJSMF0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:59:31Z"
    mac: ENC[AES256_GCM,data:sRVv7o1h+dvAx0uII5CdHxoZU2MHlFhYmWyiSNs7fDvqwo/saeFuo2ZokufZHdrzb8BmMvVv2al53DEbueFTqFDeMjvkSd7m8B3s2Ookn4MaDbHC3+fwNMfWm1jfUiuGqbz8tU5bHgAm8TDYjdSCq1HAFVQVl3lXS/8i1K3Fo7s=,iv:TkxHTgcXbjzs4FGhqfNHjA6Ndt0L15MyJqacbYZ9s5w=,tag:l+0bL1nFcbOL7NGIpERfyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
