apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cyiPksg9Ocy/sdBX,iv:5rcaPRg/iDHhc5EuO6x7DMqYZgA5PDPA7R+ZRHHpbto=,tag:rq+HB0hYIvVv4Zg/iOvOMw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:o1TrpICyin0jRliGfk4zck4T4hMz9A==,iv:SmXLnrTikfApxe3UvIZS2iI+pCZAsKDyDlQ2cigMnB0=,tag:iXfw6hIQJFK+kMrZ9BaOJw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:t2w0S0U+vxxGnHyOqM19FelRouhIIrlr3sCoSKntW2GlFvhy,iv:eTrhacUsU0BJg7742wW5TixaV7vWhefeYYipL8fZzGY=,tag:l7Z2PHzrp49HVYYYOdyC/g==,type:str]
    SECERT_ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:raXHGWQFfh6veDkg0N/tvmPyvtFbCSDRN5MkPH0GvDPAOLX7GYAMkFAeI7CsUPl/rhx5P1RbT31YnDYZ,iv:c+OCxDdZzLr31xl+r743FQ5AdTTrzfgp9pI9jLerFTE=,tag:oQB396ZNDu0sPudzG67Tsg==,type:str]
    GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:qu/VBIx9MG6RDwhtQbzftmKHzrphpwKVBRlJO4Q58/A=,iv:4xGxfswOWFOYhtr0gIEze7GkbDLhzYxifSewqcfsvRI=,tag:rvWqSDmf8EfttaVLPBsq0w==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:Pz8y2jLYuO1RlXA=,iv:MROxL95oCYzTUYpZi685shdlSYeOG1mQ0k9B0Uz5TLY=,tag:hgA3BvXffoHfcdWvCEkPKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSjVNdjdsMUpiRUlQSWsw
            SnlLMTlTb1FESVlYMWFBaGlYeFVSQVZ4c1hzCkhUWHlqZytLRndPamhzMTV5SnN1
            S3hLWG4vbGl5UHFVdTFJU2hsVlhyR2cKLS0tIDVLRSszY3h6RkJ1UHRkSFczZUZN
            dUpZaGZCUGljZUdxaWtLcTMxZk1GMmMKOO1gzfQA7WaSKB948JcBUCjlDn0oyerB
            +vzWzqKDHQQSJfdHLCbxAgsxNvwvaBIhVIgtsqA0LIFVxsGTNDmskA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:59:31Z"
    mac: ENC[AES256_GCM,data:XdYQ78ngtnp5UDkXqqB0Vxo0O6qc/Fk+pDE/vYSrk/ZuPMWOIODp871feIkLWs2oetL160VSmSIezRgYyl7jmS5Ps9GV2CS6+VhcvCPdNNyqA1IQB5VE+ibfjSmcTsksIuUXhNsA7jNR+Uutu/Y0jtb4smVuAAyw4Jfrl0Eq6R4=,iv:BCnIwNQwCF4uA0K+UsXat89Ky7IgRiClP/FxektuyV0=,tag:el+MoOAJidWhd67zyXVTqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
