apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Zp6mNz/FFxTblIWy,iv:yYV4zcVZqmS4heSSZtyi/tyVjZrhkge16PxyuM9XHP8=,tag:JqddD+32KxfMFNrH/igohw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:LGxMlIrRJ/iTOBNyKDSaUW238bVgVQ==,iv:b/8dTjhbEeoPvyb0EibGZVk9PKur3XsjNQJUv39yVLw=,tag:piJ05T+heqTxwS9hHX0R+w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xRcS3gK84nMtn+bDi6k3nkoj46d3Ac+aL/azFebhqICyAoYx,iv:wsAMENNXj20sYwoCkp/A9pPQEVxbF6YceofQtm+U2Cg=,tag:Nkc4z6IupyuQGDl2CeLTKA==,type:str]
    SECERT_ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:bQyIK7ArRNnlKGxy7QPZ8Gk88a2Na4jLMOgw7EvL1F21CPRcnRySoi1PM6YhonTmUyEsER00bjz2Kuhb,iv:YRgZERx4qPwbUDxIqyQnRu9TABS40YWabncjKNEFpwM=,tag:GLS7+DndbjFvL7Uo59Wv/g==,type:str]
    GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:mbzGGm6wHIuDCRSQSORdLdzZJdENzQ/L8M0ylf/fq8k=,iv:R/ThfcKTu+Q2AAo/6ZDnX1wCfFhCobQ7Rw9LZWfEQbM=,tag:gsZSaTDG4QV8I5LR4y2Miw==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:ZJcvPV+w07Qc250=,iv:4d5PBwzram4kQ3NwdzT1zfOYBiXYB0CMtH98kCF6cTg=,tag:MWXfuAo9USpH5hGze5tfrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNVU4dmZ6UEF0QkVuWVZU
            MmFQWGJNMnRiWENHU1R2WmpsUllHV3dGMVRFCnA5MHBxK05qQ2wxdjZRYTMvY1V4
            SmdOZzFVQlR4eW1tbHY2VDlld0JRSUkKLS0tIDZNTG05NFJrS3U5WVVrd0c5cWcw
            RDFkNUZ5alFpL1BsMDRob3p3MG9Kb2cKSM88xjr3Rfz7DZpv2k4EBRArSbm4/bHP
            +hj1u+nxw+TiRTq14KBjs8nvi5LA/YTy0r1gx5QeiNr+RaRgOO6f2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T07:48:37Z"
    mac: ENC[AES256_GCM,data:WxzOHRy0Cyfdc9SoavGqRIH4edzsMzcncXSgLX3u8jgL1KJ2MROuMOyigGzBDjSByFjH+jIey+nKyM8HBQrJjnKTAD7pXkERErnOX5eBF6ffgnzXcKJTsTOsf7LYa24e/1qZ9PWbor1hvIUG9Yj84q2MVOAaYO72ShZUZf69qdw=,iv:UtvKXr4IqRH3HU6IhVTkiJOdtBumR6kusL+iwJywYT0=,tag:XRfWvMZdMULFzi/KOyUgOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
