apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:XoJTdErjGaReysDKc9Me48wAV6O6nJzxDSHIOVSIRbc=,iv:jo6hWt8xf4f5EdVIn3blOAubbUX9z/KhnoiKD8d8PlU=,tag:5xrLp0Sm1Iqhnp1CJ6gVkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa3NFZEgzTEhxNUE5dVpD
            eUplREdnNGlodGUyQXRuTm5hNytnMHZ1RERjClhZOThGdjVyaDVHZ3pkL1FETXh5
            clhINU5tclA1L0NnWUljSUc5c3h6alEKLS0tIHdCazQ0eWR4ZFROeVZFeHUwYi80
            ZWJPM25zODJidTZBakJGV2twalgyWEkKGig54Cl6Ey4tefLQvbbyiWDWOXwZQ9xt
            9ybindf3bKKKuMn4iskw/8TxGVntH6nm/TnnJu6w6nAA8PDV4CbA6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-15T06:11:44Z"
    mac: ENC[AES256_GCM,data:PG4bXZgD5e2LTH44wp8Ci4aJmvSPirtfenGoUCUkcPwyEQwgkk0pOc4/comLjktIZSttDG4dln6bthZRWIGRKLApNzfI77EfLpnPEo+GwnSp7SU92lZ/PcyXSVWL2hZ3y7+ollx3zHDcSLhNDPVFk2mxARgmOWtcU1fTfnN/iec=,iv:5zzKNHHfwe0kqTeZMIk1v3HBVYAJBv7b+0YwHhDXVyk=,tag:eVIuo3oQTFTXKdHgsDrpBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
