apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:qCcO+ye2wFSrvrP3k8TyeVCYOm/xDRuDk0Q0x+zMMUU=,iv:Z5Oa0fDHLgN6fEar/Xyi6ZKRd6eZ1qQYpzOzMRJZ4Y0=,tag:hdLYL4d6sK2gwe78Nx28TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieUJ0c240dno1K2dCQ0Rn
            YmI3TXpNMFAvTEg3K3JHRWhmMnFXeUxHeFFZCk5pOFlpWmFvNktwRXpxa3AyUkxD
            SjFKQ2FTa3dXdXR2QXFEbkovdmV1MjgKLS0tIHA2eHpEMGRzQUxLQ2NHSGoxUk92
            SHlVSGtHRytlaHlLSmtaZGIra3VqN3cKcGQDqnQfnQnrTN40p+O9IZ7M4QDtF63K
            LyTFXe7n4SdSCs8vXrSS07ADmEf05HRKo8r4AQtNirlhxIRNxhrGGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T07:48:37Z"
    mac: ENC[AES256_GCM,data:ZuKmhw6tUyE7moCoRIU/t3Gt1+MCEKxctOVUKjJA4CF8Kxj//u+cBonoYSVJmGru8h/Z3tCFtKmI9eHRF7xK4Qh5FpXiIklmU7YHVoTk/fwxlv+e2xdpGvBS+eGZ04MOzyFw3GsvSMqdCIsiSQMmwWdzFMT400wbfTDFOaOmv4Y=,iv:PCd2I2p1hcruXYXiNiBXyezDYfCFbtD33Zcy4yCtGeY=,tag:JAooYPM8Xn6CfC1tXX7rlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
