apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:8wVVEmV1hJ6jzwxF7FYy0xal9mtxApngQeA6HxMKWFtyF+RDFGmyVA==,iv:qgVCOyt0wOSwzBzK213CorLacJ1spKc4LWFJ7NEqEuM=,tag:Pk88ZNxcBW1kOZ6xIlG/yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRzBrUG1nVFo3bGZXSnNJ
            N2diWmpsaUFnY1pyRUt3aGVDUWcxZG5HUENNCk1QSm1XU0Nvamk0SExRNTRoNGtx
            UkxUK3lwUVZUeVZZYWttNTJHTHZyL28KLS0tIElZSVRCdG9UamxQc2ZESTZVUmhx
            VUtlb0J4dUJ3VHBXall6VUdTTU95ZXcKXGvc1Lb4c7SqyzHD4x6QLgbAwEcvJ099
            C2aQ2uKYlwqLsWyMiC/yBmHSkENkMuG/I+Hw3rcgs0G4rLrpZfMnLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T07:48:37Z"
    mac: ENC[AES256_GCM,data:oEj3TgO4y2KBBiwH6B1xfihNJ0EdBd8+DTqnMkbuA5MgFdSA1n361GwceoCutqPWYrSbx91lDnHlhz+7/oZXANRxs7PeuFYIscqNIeNzBVvyG9/AnHFllNB/2D2D+xtF1hAbfOMCsF3cRIQgOxCuVY4vBUDBP5uIIYIlPkCZs2s=,iv:rlJFWKuXi9iNsiMl6GuNAQz64of+FzYC8Tzc8KSBE0s=,tag:cPsZVUzskYNQ3cJsrvHUbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
